### ISSUE TITLE
Pypi package is gone

### ISSUE THREAD

**Issue by mpourmpoulis** [mrob95/Speakit#1]
Greetings Mike  and many thanks for the Nice and handy package! Unfortunately yesterday I noticed the distribution from pypi appears to be gone

https://pypi.org/search/?q=speakit

And I felt like letting you know in case something was off

**Comment by mirober** [comment]
Huh, that's odd! I've republished it - https://pypi.org/project/speakit/ - thanks for letting me know :)

**Comment by mpourmpoulis** [comment]
Thanks for quickly resolving this Mike 👍
